### ISSUE TITLE
request.namespace empty in hiera compatability plugin

### ISSUE THREAD

**Issue by agarstang** [crayfishx/jerakia#47]
When using the hiera plugin the [namespace is set to an empty array](https://github.com/crayfishx/jerakia/blob/master/lib/jerakia/lookup/plugin/hiera.rb#L16).

Despite the fact that I can see the namespace is parsed from the "name::space::key" string at some point in the debug log, the request.namespace variable remains empty.
```
 [2016-06-08T11:42:31.237000 #25790] DEBUG -- : Request initialized with {:key=>"sql_connections", :namespace=>["profile", "blah"]
```

**This breaks confines/excludes.**

**Comment by agarstang** [comment]
I can get round this by doing.

```ruby
confine request.key.split("::")[0], [
      "namespace"
    ]
```

**Comment by crayfishx** [comment]
So the hiera plugin is not ideal, but it exists to give hiera users a way of using Jerakia without having to munge all their data - the only way to make the file datasource behave with a hiera layout is to not have a namespace.... the hiera plugin does provide a method called `calling_module` which is familar to hiera users as `%{calling_module}`, so actually a better way of doing this would be 

```ruby
confine plugin.hiera.calling_module, "foo"
```
This should probably be documented.

Note - I came across an issue with `calling_module` which I fixed in #46 today when looking at your other PR

**Comment by crayfishx** [comment]
@agarstang out of interest, why are you using the hiera plugin with the http datasource?  The hiera plugin mostly exists to make the file datasource compatible with hiera filesystem layouts... eg

Hiera

```
# cat /path/scope.yaml
module::var: val
```

versus Jerakias more separated format....

```
# cat /path/scope/module.yaml
var: val
```

I can't think of any use cases for using this plugin with the http datasource...??

**Comment by agarstang** [comment]
My use case is related to #48.

I wanted to keep my URI/searchpaths generic based on facts from the scope. The API just returns a JSON document containing any keys it considers valid for that URI.

If I was to add the the namespace to the URI I'd have a (not too obvious to the people creating the namespaces) limit as I'd have to search like this:
```ruby
datasource :http, {
       :host    => "192.168.192.183",
       :port    => 8081,
       :output  => "json",
       :paths  => [
         "/configuration/#{request.namespace[0]}",
         "/configuration/#{request.namespace[0]}/#{request.namespace[1]}",
         "/configuration/#{request.namespace[0]}/#{request.namespace[1]}/#{request.namespace[2]}",
         "/configuration/#{request.namespace[0]}/#{request.namespace[1]}/#{request.namespace[2]}/#{request.namespace[3]}"
       ]
     }
```

**Comment by agarstang** [comment]
Unless... I iterated over the namespace...

**Comment by crayfishx** [comment]
This looks like the kind of edge case that Jerakia solves really well, being a ruby DSL..  While you *could* put that iteration into the policy, a nicer, more re-usable (within your org) way would be to write your own plugin and put it in the plugindir  (or as a gem)

Something like

```
class Jerakia::Lookup::Plugin
  module Myorg

    def build_paths
       paths = []
       namespace.length.times { |x|
         paths << "/configuration/" + namespace[0..x].join('/')
      }
    end
  end
end
```

And then your policy becomes

```ruby
lookup :default, :use => :myorg do
  datasource :http, {
       :host    => "192.168.192.183",
       :port    => 8081,
       :output  => "json",
       :paths  => plugin.myorg.build_paths
       ]
     }
 end
```

**Comment by agarstang** [comment]
This can be closed as I am happy with the response.

Unless you feel it would be nice to have the namespace variable still populated with parsed namespace, despite the hiera plugin adding it to the key (it does appear to get parsed at some point in the debug log anyway)? This means that confines would still work as documented even with the hiera plugin.

**Comment by crayfishx** [comment]
@agarstang that would mean adding some logic to the file datasource, the hiera plugin "hacks" the request to fool the file data source into looking things up "hiera style".  It's certainly worth considering, I hadn't thought about the impact on confine - for now, maybe we just document that if you're using the hiera plugin then you should use `plugin.hiera.calling_module` instead of `request.namespace` in the lookup.   It's something we should keep on the radar though
