### ISSUE TITLE
HTTP datasource does not utilise namespace

### ISSUE THREAD

**Issue by agarstang** [crayfishx/jerakia#48]
This is maybe a feature request rather than a bug.

The HTTP datasource appears to ignore the namespace when searching. It only searches for the key. Unlike the File datasource which uses the namespace to construct the search path.

While I don't think it should append to the URI (as this removes flexibility on the services you can call). I think there should be an option for the YAML/JSON formats to process the namespace as part of the tree. I.e. `name::space::key` searches:
```json
{
    "name": {
        "space": {
            "key": "value"
        }
    }
}
```

That way it keeps the association between the namespace and the key. This could be important as the namespace qualifies the key (there could be other keys with the same name).

I can get round this by using the hiera plugin (although this is broken in my use case at the moment - see #47) however I'd like to move away from:
```json
{
        "name::space": {
            "key": "value"
        }
}
```

**Comment by crayfishx** [comment]
You're right - this isn't so much of an oversight as it is by design,  the HTTP datasource doesn't assume what kind of service you are connecting to so it's assumed that if you need it as part of the lookup you'll put the namespace in the the URI.....

I like your idea about using namespace in the output parsing, although maybe a more generic way would be to use (write) an output filter to do this so it's not specifically tied to http
