### ISSUE TITLE
Easier debugging

### ISSUE THREAD

**Issue by ggeldenhuis** [crayfishx/jerakia#65]
It would be great to be able to see jerakia debug messages as part of my puppet run, when invoking `--debug` with the puppet command.

**Comment by crayfishx** [comment]
I guess the best way here would be to create some kind of pluggable logging facility, so you could have a puppet logging facility instead of the native Jerakia::Log one and tie that in with the hiera backend/data binding terminus.

One thing to consider, even simple Jerakia lookups would spit out about 50 lines of debug *per lookup*, so this may be a bit too verbose.... there may be a use case for removing some of the debug information that's not really that useful (or was useful when I was writing things but doesn't serve much purpose now)

**Comment by ggeldenhuis** [comment]
I feel intensely uncomfortable in removing useful verbosity. A way to hide a high level of verbosity would probably be favourable I think. As jerakia gets more developers on board, developer level debugging would be very helpful and would additionally serve as a way to understand the inner functioning and catch those strange edge case bugs.

**Comment by crayfishx** [comment]
Fair enough, my estimate of 50 lines was probably a bit high anyway

**Comment by crayfishx** [comment]
This idea is going to need some revising...  1.2 is going to ship with "Jerakia Server" which will be more of a standalone Jerakia that will have integration points to tools such as Puppet over a REST API and eventually we will deprecate the current hiera backend and data_terminus ruby bindings.  Therefore just piping the logger object somewhere else will no longer be feasable.

I don't think it's going to be workable (or sensible) to try and expose the whole debug log over REST API, though I think at the very least we need to adopt an "explain" option in API to give some verbosity about where and how a lookup happened, which would directly map back to the explain features in Puppet 4.9 lookup feature.

As for the full debug log, I think that should just be done to /var/log/jerakia.log - or alternatively you could start jerakia server in the foreground and log to STDOUT for dev debugging.
